// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.14.0
// source: openapi/v3/annotations.proto

export const protobufPackage = "openapi.v3";
